/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113146-g56c5930ec3-20231230"
#endif /* AVUTIL_FFVERSION_H */
